---

- name: assert all vars are set
  assert: 
    that: "{{ item }} != '' "
  with_items:
    - required_space_mb

- name: get free space
  shell: df -Hm /opt | tail -n 1 | awk {'print $4 '} 
  changed_when: no
  register: test

- set_fact: 
    free_space_mb: "{{ test.stdout }}"

- name: validate required
  assert:
    that:
      - free_space_mb|int > required_space_mb|int
    fail_msg: "free space test failed: {{ free_space_mb }} < {{ required_space_mb }}"
    success_msg: "free space test passed: {{ free_space_mb }}"
